name: Actualizar resultados Triplex

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta en el minuto 0 de cada hora, todos los días
    
  workflow_dispatch: # Permite lanzarlo manualmente cuando quieras

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Ejecutar script de actualización
        run: node update-results.js

      - name: Guardar y subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática de resultados del Triplex" && git push)
          
